service_type = "b"

service_attrib1 = 10
service_attrib2 = "test WOW"
service_attrib3 = false
service_non_injectable = "how could this be injected???"

common_attrib1 = 55
common_attrib2 = "test common"

service_precedence_attrib1=10